[package]
name = "app"
version = "0.1.0"
description = "Intel GenAI Chat Interface - A Tauri App"
authors = ["Intel Developer"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.3.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.6.2", features = [] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2"
# HTTP client with proxy support
reqwest = { version = "0.12", features = ["json", "stream"] }
# For async runtime
tokio = { version = "1.0", features = ["full"] }
